import os
os.makedirs('/root/workspace/Penelope/products', exist_ok=True)
os.system('/root/penelope_env/bin/pip install fpdf2 --break-system-packages -q 2>/dev/null')

from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 10)
        self.cell(0, 8, 'GUERILLA HOLDINGS LLC | guerillaholdings.lemonsqueezy.com', new_x='LMARGIN', new_y='NEXT')
        self.line(10, 20, 200, 20)
        self.ln(2)
    def footer(self):
        self.set_y(-12)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(120,120,120)
        self.cell(0, 8, f'Page {self.page_no()} | Guerilla Holdings LLC | April 2026', align='C')

def add_h1(pdf, text):
    pdf.set_font('Helvetica', 'B', 20)
    pdf.set_text_color(0,0,0)
    pdf.ln(6)
    pdf.multi_cell(0, 10, text)
    pdf.ln(2)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(4)

def add_h2(pdf, text):
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(20,20,20)
    pdf.ln(4)
    pdf.multi_cell(0, 7, text)
    pdf.ln(1)

def add_body(pdf, text):
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(60,60,60)
    pdf.multi_cell(0, 5.5, text)
    pdf.ln(2)

def add_bullet(pdf, text):
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(60,60,60)
    pdf.cell(8)
    pdf.multi_cell(0, 5.5, '- ' + text)

# === PRODUCT 1: AI Revenue Playbook ===
pdf = PDF()
pdf.set_margins(15, 22, 15)
pdf.add_page()
pdf.set_font('Helvetica','B',26)
pdf.ln(15)
pdf.multi_cell(0,12,'AI Revenue Playbook\nGuerilla Holdings Complete System',align='C')
pdf.ln(6)
pdf.set_font('Helvetica','',12)
pdf.set_text_color(80,80,80)
pdf.multi_cell(0,7,'Guerilla Holdings LLC | trustchainservices.com | April 2026',align='C')
pdf.ln(20)
pdf.set_font('Helvetica','',10)
pdf.multi_cell(0,6,'This playbook contains the operational frameworks, agent architectures, and revenue systems used by Guerilla Holdings LLC across specialty transport, social enterprise, and digital commerce. Licensed for individual use only.',align='C')

pdf.add_page()
add_h1(pdf, 'Part 1: AI Agent Architecture')
add_h2(pdf, 'The Hybrid LLM Model')
add_body(pdf, 'The Penelope autonomous agent stack uses a hybrid approach: Claude Opus for orchestration and high-complexity decisions, Gemini 2.5 Flash for bulk execution. Cost: ~$0.10 per 1,000 content pieces vs $50+ manually.')
add_bullet(pdf, 'Orchestration: Claude Opus 4.6 via API (planning, synthesis, complex decisions)')
add_bullet(pdf, 'Execution: Gemini 2.5 Flash (bulk content, research, product scoring)')
add_bullet(pdf, 'Infrastructure: DigitalOcean 2vCPU/4GB RAM droplet ($24/month)')
add_bullet(pdf, 'Shell bridge on port 5099 for autonomous command execution')
add_h2(pdf, 'Core Revenue-Generating Agents')
add_body(pdf, '1. Product Scout Agent: Scrapes Amazon/Google Trends/AliExpress every 4 hours. AI-scores on margin, competition, velocity. Saves complete product packages.')
add_body(pdf, '2. Content Army Agent: Generates 10-platform content package per product. LinkedIn, Instagram, TikTok, Twitter, Reddit, YouTube, 3-email drip, Amazon affiliate, SEO blog, Pinterest.')
add_body(pdf, '3. Grant Hunter Agent: Daily 8AM scan of federal/California grant databases. Auto-drafts applications. Telegram alert with opportunity score and deadline.')
add_body(pdf, '4. Shopify Intel Agent: Daily competitor monitoring via Firecrawl. Price changes, new products, ad creative. Weekly Telegram brief.')

pdf.add_page()
add_h1(pdf, 'Part 2: Shopify CRO — The $25M Page Formula')
add_h2(pdf, 'Above-the-Fold Requirements (No Scroll)')
add_body(pdf, 'Research from $25M and $3M Shopify product pages shows these 7 elements must be visible before scrolling:')
add_bullet(pdf, 'Benefit-led headline (what it does, not what it is)')
add_bullet(pdf, 'Star rating + review count immediately visible')
add_bullet(pdf, '4-6 images: product + lifestyle, multiple angles')
add_bullet(pdf, 'High-contrast Add to Cart button, uncluttered')
add_bullet(pdf, 'Trust badges below CTA: free shipping, money-back, secure')
add_bullet(pdf, 'Price with savings highlighted')
add_bullet(pdf, 'Sticky ATC bar following on scroll (+5-12% mobile CVR)')
add_h2(pdf, 'Proven Conversion Numbers')
add_bullet(pdf, 'Free shipping progress bar: +12-18% average order value')
add_bullet(pdf, 'Amazon Buy with Prime: +20-38% CVR')
add_bullet(pdf, 'SMS cart recovery: 98% open rate, 2x email recovery')
add_bullet(pdf, 'Seel purchase protection: +10-15% AOV, +16.5% LTV')
add_bullet(pdf, 'Product video on page: +80% CVR average')
add_h2(pdf, '30-Day Sprint Plan')
add_body(pdf, 'Week 1 (Free, under 30 minutes): Install EA Sticky ATC, EA Free Shipping Bar. Add star rating above fold. Write benefit headlines for top 3 products. Add trust badges below every CTA.')
add_body(pdf, 'Week 2 (Social proof): Klaviyo abandoned cart 3-email sequence. UGC images on top 5 pages. Per-product FAQ answering top 3 objections.')
add_body(pdf, 'Week 3 (AOV): ReConvert post-purchase upsell. Frequently Bought Together bundles. Subscription option on consumables.')
add_body(pdf, 'Week 4 (Scale): A/B test headline A vs B on highest-traffic product. 10 micro-influencer DMs. SMS cart recovery via LiveRecover or Postscript.')

pdf.add_page()
add_h1(pdf, 'Part 3: Revenue Channel Stack')
add_h2(pdf, 'Amazon Associates (Tag: guerillahold2-20)')
add_body(pdf, 'Commissions: Vehicle/transport equipment 4-8%, Medical/safety 4.5%, Technology 2.5-4%. Best content: problem post + solution + comparison table + result claim.')
add_h2(pdf, 'LemonSqueezy Digital Products')
add_body(pdf, 'Store: guerillaholdings.lemonsqueezy.com | Store ID: 332591. Activation requires Stripe connection at app.lemonsqueezy.com > Settings > Billing.')
add_h2(pdf, 'CALLUX Revenue Model (65/35 Split)')
add_bullet(pdf, 'Tier 1: General Transport $18-25/hr')
add_bullet(pdf, 'Tier 4: Mortuary/Non-Emergency $35-55/hr')
add_bullet(pdf, 'Tier 6: Specialty/Research $55-85/hr')
add_bullet(pdf, 'Tier 4 driver, 3 runs/day = $315-495/day gross, $204-$322 net')
add_h2(pdf, 'GAFC Grant Targets')
add_bullet(pdf, 'CalVIP: Up to $500,000 — violence prevention, GAFC qualifies')
add_bullet(pdf, 'Everytown Community Safety Fund: $50K-$200K')
add_bullet(pdf, 'Sacramento Stockton Blvd Action Grant: $5K-$25K')
add_bullet(pdf, 'Unlock federal grants: MWBE cert at calosba.ca.gov + SAM.gov registration')

path = '/root/workspace/Penelope/products/ai_revenue_playbook.pdf'
pdf.output(path)
size = os.path.getsize(path)
print(f'Product 1 created: {path} ({size:,} bytes, {pdf.page} pages)')

# === PRODUCT 2: CALLUX Driver Guide ===
pdf2 = PDF()
pdf2.set_margins(15, 22, 15)
pdf2.add_page()
pdf2.set_font('Helvetica','B',24)
pdf2.ln(15)
pdf2.multi_cell(0,11,'CALLUX Specialty Transport\nDriver Certification Prep Guide',align='C')
pdf2.ln(6)
pdf2.set_font('Helvetica','',12)
pdf2.set_text_color(80,80,80)
pdf2.multi_cell(0,7,'TrustChain Services | CALLUX Platform | April 2026',align='C')

pdf2.add_page()
add_h1(pdf2, 'The 6-Tier CALLUX Certification System')
add_body(pdf2, 'CALLUX operates a merit-based 6-tier certification system for specialty transport operators in Sacramento, NorCal, Bay Area, and Reno. Higher tiers unlock institutional contracts, premium rates, and priority dispatch.')
add_h2(pdf2, 'Tier 1: General Transport ($18-25/hr)')
add_bullet(pdf2, 'Requirements: Clean driving record (5 years), valid CA license, basic background check')
add_bullet(pdf2, 'Vehicle: Any clean, insured personal vehicle')
add_bullet(pdf2, 'Cargo: General non-hazardous, non-medical items')
add_h2(pdf2, 'Tier 2: Medical Equipment ($22-30/hr)')
add_bullet(pdf2, 'Requirements: Tier 1 + HIPAA awareness training, equipment handling certification')
add_bullet(pdf2, 'Vehicle: Clean interior, climate-controlled preferred')
add_bullet(pdf2, 'Cargo: Non-critical medical equipment, supplies')
add_h2(pdf2, 'Tier 3: Sensitive/Temperature Cargo ($28-38/hr)')
add_bullet(pdf2, 'Requirements: Tier 2 + chain of custody training, temperature log certification')
add_bullet(pdf2, 'Vehicle: Temperature monitoring capability required')
add_bullet(pdf2, 'Cargo: Pharmaceutical samples, biologics, time-sensitive specimens')
add_h2(pdf2, 'Tier 4: Mortuary/Non-Emergency ($35-55/hr)')
add_bullet(pdf2, 'Requirements: Tier 3 + dignity protocols training, institutional compliance')
add_bullet(pdf2, 'Vehicle: Converted transport vehicle or approved configuration')
add_bullet(pdf2, 'Cargo: Non-emergency decedent transport under institutional contract')
add_h2(pdf2, 'Tier 5: Hazardous Materials ($45-65/hr)')
add_bullet(pdf2, 'Requirements: Tier 4 + DOT Hazmat certification, manifest training')
add_bullet(pdf2, 'Vehicle: DOT-compliant, placarded for hazmat class')
add_bullet(pdf2, 'Cargo: Class-appropriate hazardous materials under DOT regulation')
add_h2(pdf2, 'Tier 6: Specialty/Research ($55-85/hr)')
add_bullet(pdf2, 'Requirements: Tier 5 + institutional vetting, research facility clearance')
add_bullet(pdf2, 'Vehicle: Research-grade transport configuration')
add_bullet(pdf2, 'Cargo: Research specimens, institutional contracts, classified materials')

pdf2.add_page()
add_h1(pdf2, 'Revenue Optimization Guide')
add_h2(pdf2, 'The 65/35 Revenue Split')
add_body(pdf2, 'CALLUX retains 35% of gross fare for platform, dispatch, insurance pooling, and institutional contract management. Drivers receive 65% of all fares plus 100% of gratuities.')
add_h2(pdf2, 'Earnings by Tier')
add_bullet(pdf2, 'Tier 1: $18-25/hr gross, $11.70-$16.25/hr net')
add_bullet(pdf2, 'Tier 4: $35-55/hr gross, $22.75-$35.75/hr net')
add_bullet(pdf2, 'Tier 4, 3 runs/day (avg 2.5hr each): $262-$412/day net')
add_bullet(pdf2, 'Tier 6: $55-85/hr gross, $35.75-$55.25/hr net')
add_h2(pdf2, 'Professional Gear Checklist')
add_bullet(pdf2, 'Vehicle tablet mount (RAM mounts recommended) — dispatch and navigation')
add_bullet(pdf2, 'HIPAA-compliant documentation organizer — chain of custody forms')
add_bullet(pdf2, 'Portable power station 300W+ — sustain equipment during shifts')
add_bullet(pdf2, 'OSHA-compliant first aid kit — required by California specialty transport code')
add_bullet(pdf2, 'Dual-channel GPS dash camera — liability protection and institutional compliance')
add_bullet(pdf2, '12V portable refrigerator — required for Tier 3+ temperature-sensitive cargo')
add_bullet(pdf2, 'Professional uniform — institutional clients evaluate professionalism first')

path2 = '/root/workspace/Penelope/products/callux_driver_guide.pdf'
pdf2.output(path2)
size2 = os.path.getsize(path2)
print(f'Product 2 created: {path2} ({size2:,} bytes, {pdf2.page} pages)')

print('\nAll products built successfully.')
print('Next step: Upload to LemonSqueezy via files API and attach to variant 1473039')
